version: 1.0.0.{build}

platform: x64

clone_folder: c:\gopath\src\github.com\favadi\osinfo

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env

build: off

test_script:
  - go test -v github.com\favadi\osinfo\...
